name: AI Code of the Day Bot

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Install dependencies
        run: dotnet restore CodeOfTheDay/CodeOfTheDay.csproj

      - name: Build bot
        run: dotnet build CodeOfTheDay/CodeOfTheDay.csproj --configuration Release

      - name: Run bot
        run: dotnet run --project CodeOfTheDay/CodeOfTheDay.csproj
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY_OWNER: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
